/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Fonte.jFrameAddingFont;
import java.awt.Font;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Arthur
 */
public class TelaAddPokemon extends javax.swing.JFrame {
    
    Font font_titulo = jFrameAddingFont.Adding_font().deriveFont(30f);
    Font font_textField = jFrameAddingFont.Adding_font().deriveFont(24f);
    Font font_btn = jFrameAddingFont.Adding_font().deriveFont(24f);
    Font textArea = jFrameAddingFont.Adding_font().deriveFont(18f);
    
    public TelaAddPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        type1Field = new javax.swing.JTextField();
        type2Field = new javax.swing.JTextField();
        generationField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        atackField = new javax.swing.JTextField();
        defenseField = new javax.swing.JTextField();
        speedField = new javax.swing.JTextField();
        heightField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BtnAddPokemon = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        classificationField = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 825));
        setResizable(false);
        getContentPane().setLayout(null);

        nameField.setFont(font_textField);
        nameField.setBorder(null);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField);
        nameField.setBounds(230, 230, 350, 40);

        type1Field.setFont(font_textField);
        type1Field.setBorder(null);
        getContentPane().add(type1Field);
        type1Field.setBounds(230, 320, 230, 40);

        type2Field.setFont(font_textField);
        type2Field.setBorder(null);
        type2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type2FieldActionPerformed(evt);
            }
        });
        getContentPane().add(type2Field);
        type2Field.setBounds(230, 410, 230, 40);

        generationField.setFont(font_textField);
        generationField.setBorder(null);
        generationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generationFieldActionPerformed(evt);
            }
        });
        getContentPane().add(generationField);
        generationField.setBounds(230, 500, 130, 40);

        idField.setFont(font_textField);
        idField.setBorder(null);
        getContentPane().add(idField);
        idField.setBounds(680, 230, 180, 40);

        atackField.setFont(font_textField);
        atackField.setBorder(null);
        atackField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atackFieldActionPerformed(evt);
            }
        });
        getContentPane().add(atackField);
        atackField.setBounds(680, 320, 180, 40);

        defenseField.setFont(font_textField);
        defenseField.setBorder(null);
        defenseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defenseFieldActionPerformed(evt);
            }
        });
        getContentPane().add(defenseField);
        defenseField.setBounds(680, 410, 180, 40);

        speedField.setFont(font_textField);
        speedField.setBorder(null);
        getContentPane().add(speedField);
        speedField.setBounds(680, 500, 180, 40);

        heightField.setFont(font_textField);
        heightField.setBorder(null);
        getContentPane().add(heightField);
        heightField.setBounds(960, 320, 130, 40);

        weightField.setFont(font_textField);
        weightField.setBorder(null);
        getContentPane().add(weightField);
        weightField.setBounds(1230, 320, 130, 40);

        jLabel1.setFont(font_titulo);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 270, 90, 50);

        jLabel2.setFont(font_titulo);
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 180, 80, 50);

        jLabel3.setFont(font_titulo);
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 360, 90, 50);

        jLabel4.setFont(font_titulo);
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Geração");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 450, 110, 50);

        jLabel5.setFont(font_titulo);
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Pokémon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(680, 190, 150, 40);

        jLabel6.setFont(font_titulo);
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ataque");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(680, 280, 100, 40);

        jLabel7.setFont(font_titulo);
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Defesa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(680, 370, 90, 40);

        jLabel8.setFont(font_titulo);
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Velocidade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(680, 460, 180, 40);

        jLabel9.setFont(font_titulo);
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Classificação");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(960, 176, 180, 50);

        jLabel10.setFont(font_titulo);
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Altura");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(960, 280, 80, 40);

        jLabel11.setFont(font_titulo);
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Peso");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1230, 270, 80, 50);

        BtnAddPokemon.setBackground(new java.awt.Color(61, 255, 139));
        BtnAddPokemon.setFont(font_btn);
        BtnAddPokemon.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddPokemon.setText("Adicionar");
        BtnAddPokemon.setFocusPainted(false);
        getContentPane().add(BtnAddPokemon);
        BtnAddPokemon.setBounds(1350, 690, 150, 60);

        BtnVoltar.setBackground(new java.awt.Color(56, 232, 238));
        BtnVoltar.setFont(font_btn);
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("<<");
        BtnVoltar.setToolTipText("");
        BtnVoltar.setFocusPainted(false);
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(80, 700, 100, 50);

        classificationField.setFont(font_textField);
        classificationField.setBorder(null);
        classificationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classificationFieldActionPerformed(evt);
            }
        });
        getContentPane().add(classificationField);
        classificationField.setBounds(960, 230, 400, 40);

        Background.setFont(font_textField);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imagem add.png"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(-20, 0, 1600, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generationFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void type2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type2FieldActionPerformed

    private void atackFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atackFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atackFieldActionPerformed

    private void defenseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defenseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defenseFieldActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void classificationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classificationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classificationFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAddPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAddPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAddPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAddPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){
            System.out.println(e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BtnAddPokemon;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JTextField atackField;
    private javax.swing.JTextField classificationField;
    private javax.swing.JTextField defenseField;
    private javax.swing.JTextField generationField;
    private javax.swing.JTextField heightField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField speedField;
    private javax.swing.JTextField type1Field;
    private javax.swing.JTextField type2Field;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
