/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Fonte.jFrameAddingFont;
import java.awt.Font;
import javax.swing.UIManager;

/**
 *
 * @author Arthur
 */
public class TelaMenu extends javax.swing.JFrame {
    
    Font font = jFrameAddingFont.Adding_font().deriveFont(32f);


    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRemovePokemon = new javax.swing.JButton();
        BtnAddPokemon = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        BtnBuscarPokemon = new javax.swing.JButton();
        Imagem_TelaMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 839));
        setResizable(false);
        getContentPane().setLayout(null);

        BtnRemovePokemon.setBackground(new java.awt.Color(0, 71, 255));
        BtnRemovePokemon.setFont(font);
        BtnRemovePokemon.setForeground(new java.awt.Color(255, 255, 255));
        BtnRemovePokemon.setText("Remover um Pokemon");
        BtnRemovePokemon.setFocusPainted(false);
        BtnRemovePokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemovePokemonActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRemovePokemon);
        BtnRemovePokemon.setBounds(160, 460, 360, 90);

        BtnAddPokemon.setBackground(new java.awt.Color(0, 71, 255));
        BtnAddPokemon.setFont(font);
        BtnAddPokemon.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddPokemon.setText("Adicionar um Pokemon");
        BtnAddPokemon.setFocusPainted(false);
        BtnAddPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAddPokemon);
        BtnAddPokemon.setBounds(160, 330, 360, 90);

        BtnVoltar.setBackground(new java.awt.Color(56, 182, 255));
        BtnVoltar.setFont(font);
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("<<");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(90, 720, 90, 50);

        BtnBuscarPokemon.setBackground(new java.awt.Color(0, 71, 255));
        BtnBuscarPokemon.setFont(font);
        BtnBuscarPokemon.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarPokemon.setText("Buscar um Pokemon");
        BtnBuscarPokemon.setFocusPainted(false);
        BtnBuscarPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscarPokemon);
        BtnBuscarPokemon.setBounds(160, 200, 360, 90);

        Imagem_TelaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu.png"))); // NOI18N
        Imagem_TelaMenu.setText("jLabel1");
        Imagem_TelaMenu.setMaximumSize(new java.awt.Dimension(1600, 800));
        Imagem_TelaMenu.setMinimumSize(new java.awt.Dimension(1600, 800));
        Imagem_TelaMenu.setPreferredSize(new java.awt.Dimension(1600, 800));
        getContentPane().add(Imagem_TelaMenu);
        Imagem_TelaMenu.setBounds(0, 0, 1600, 800);
        Imagem_TelaMenu.getAccessibleContext().setAccessibleName("MenuImagem");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaInicial TI = new TelaInicial();
        TI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnRemovePokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemovePokemonActionPerformed
        // TODO add your handling code here:
        TelaRemovePokemon TR = new TelaRemovePokemon();
        TR.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BtnRemovePokemonActionPerformed

    private void BtnAddPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddPokemonActionPerformed
        TelaAddPokemon TADD = new TelaAddPokemon();
        TADD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAddPokemonActionPerformed

    private void BtnBuscarPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPokemonActionPerformed
        TelaBuscaPokemon TB = new TelaBuscaPokemon();
        TB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBuscarPokemonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        }catch(Exception e){
            System.out.println(e);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddPokemon;
    private javax.swing.JButton BtnBuscarPokemon;
    private javax.swing.JButton BtnRemovePokemon;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel Imagem_TelaMenu;
    // End of variables declaration//GEN-END:variables
}
